export default {
    // CONFIGURATION
    FETCH_CONFIG: 'FETCH_CONFIG',
    FETCH_BRIDGE_IP: 'FETCH_BRIDGE_IP',
    FETCH_USERNAME: 'FETCH_USERNAME',
    CHANGE_LOADING: 'CHANGE_LOADING',

    // GROUPS
    FETCH_ALL_GROUPS: 'FETCH_ALL_GROUPS',

    // FETCH_GROUP: 'FETCH_GROUP',
    // CREATE_GROUP: 'CREATE_GROUP',
    // CHANGE_GROUP: 'CHANGE_GROUP',
    // DELETE_GROUP: 'DELETE_GROUP',

    // // LIGHTS
    FETCH_ALL_LIGHTS: 'FETCH_ALL_LIGHTS',

    // FETCH_NEW_LIGHT: 'FETCH_NEW_LIGHT',

    // FETCH_LIGHT: 'FETCH_LIGHT',
    // CHANGE_LIGHT: 'CHANGE_LIGHT',
    // DELETE_LIGHT: 'DELETE_LIGHT'
}