export default {
    // CONFIGURATION
    FETCH_CONFIG: 'FETCH_CONFIG',
    FETCH_BRIDGE_IP: 'FETCH_BRIDGE_IP',
    ADD_BRIDGE: 'ADD_BRIDGE',
    DELETE_BRIDGE: 'DELETE_BRIDGE',
    CHANGE_BRIDGE: 'CHANGE_BRIDGE',
    CHANGE_BRIDGE_IP: 'CHANGE_BRIDGE_IP',
    FETCH_USERNAME: 'FETCH_USERNAME',
    CHANGE_USERNAME: 'CHANGE_USERNAME',
    DELETE_USERNAME: 'DELETE_USERNAME',
    CHANGE_LOADING: 'CHANGE_LOADING',
    CHANGE_THEME: 'CHANGE_THEME',
    CHANGE_STATUS : 'CHANGE_STATUS',

    // GROUPS
    FETCH_ALL_GROUPS: 'FETCH_ALL_GROUPS',
    CHANGE_GROUP_STATE: 'CHANGE_GROUP_STATE',
    CHANGE_GROUP_ATTR: 'CHANGE_GROUP_ATTR',
    CREATE_GROUP: 'CREATE_GROUP',
    FETCH_GROUP: 'FETCH_GROUP',
    DELETE_GROUP: 'DELETE_GROUP',

    // LIGHTS
    FETCH_ALL_LIGHTS: 'FETCH_ALL_LIGHTS',
    FETCH_LIGHT: 'FETCH_LIGHT',
    // FETCH_NEW_LIGHT: 'FETCH_NEW_LIGHT',
    CHANGE_LIGHT_STATE: 'CHANGE_LIGHT_STATE',
    CHANGE_LIGHT_ATTR: 'CHANGE_LIGHT_ATTR',
    DELETE_LIGHT: 'DELETE_LIGHT',

    // SCENES
    FETCH_ALL_SCENES : 'FETCH_ALL_SCENES',
    CREATE_SCENE : 'CREATE_SCENE',
    DELETE_SCENE : 'DELETE_SCENE',

    // SCHEDULES
    FETCH_ALL_SCHEDULES : 'FETCH_ALL_SCHEDULES',
    CREATE_SCHEDULE : 'CREATE_SCHEDULE',

    // AUTHENTICATION
    CHANGE_AUTHENTICATION_STATE : 'CHANGE_AUTHENTICATION_STATE',
    CHANGE_HARDWARE_SUPPORT : 'CHANGE_HARDWARE_SUPPORT',

    // CLOUD
    CHANGE_CLOUD : 'CHANGE_CLOUD',
    CHANGE_CLOUD_TOKEN: 'CHANGE_CLOUD_TOKEN'

}