export default {
    // CONFIGURATION
    FETCH_CONFIG: 'FETCH_CONFIG',
    FETCH_BRIDGE_IP: 'FETCH_BRIDGE_IP',
    ADD_BRIDGE: 'ADD_BRIDGE',
    CHANGE_BRIDGE: 'CHANGE_BRIDGE',
    CHANGE_BRIDGE_IP: 'CHANGE_BRIDGE_IP',
    FETCH_USERNAME: 'FETCH_USERNAME',
    CHANGE_USERNAME: 'CHANGE_USERNAME',
    CHANGE_LOADING: 'CHANGE_LOADING',
    CHANGE_THEME: 'CHANGE_THEME',
    // GROUPS
    FETCH_ALL_GROUPS: 'FETCH_ALL_GROUPS',
    CHANGE_GROUP_STATE: 'CHANGE_GROUP_STATE',
    CREATE_GROUP: 'CREATE_GROUP',
    FETCH_GROUP: 'FETCH_GROUP',
    DELETE_GROUP: 'DELETE_GROUP',
    // // LIGHTS
    FETCH_ALL_LIGHTS: 'FETCH_ALL_LIGHTS',
    // FETCH_NEW_LIGHT: 'FETCH_NEW_LIGHT',
    CHANGE_LIGHT_STATE: 'CHANGE_LIGHT',
    DELETE_LIGHT: 'DELETE_LIGHT',
    // SCHEDULES
    FETCH_ALL_SCHEDULES : 'FETCH_ALL_SCHEDULES',
    CREATE_SCHEDULE : 'CREATE_SCHEDULE',
    // AUTHENTICATION
    CHANGE_AUTHENTICATION_STATE : 'CHANGE_AUTHENTICATION_STATE',
    CHANGE_HARDWARE_SUPPORT : 'CHANGE_HARDWARE_SUPPORT'

}